name: Lint (Ruff + Black --check)

on:
  # Run on any branch push when relevant files change
  push:
    paths:
      - "**/*.py"
      - ".github/workflows/lint.yml"
      - "pyproject.toml"
      - "requirements-dev.txt"
  # Run on any pull request (safe: read-only token)
  pull_request:
    paths:
      - "**/*.py"
      - ".github/workflows/lint.yml"
      - "pyproject.toml"
      - "requirements-dev.txt"
  # Manual run from Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Ruff + Black (check)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dev tools
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt
        # Using pinned versions from requirements-dev.txt keeps CI deterministic.

      - name: Ruff check
        run: ruff check .

      - name: Black check
        run: black --check .
